sudo: false
language: php
dist: trusty
matrix:
  fast_finish: true
  include:
  - php: '5.4'
  - php: '5.5'
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
    env:
        - DEPLOY=1
        - SNIFF=1
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- if [[ "$SNIFF" == "1" ]]; then git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git
  $PHPCS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b 7.1.4 --depth 1 https://github.com/wimg/PHPCompatibility.git
  $SNIFFS_DIR/PHPCompatibility; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs --config-set installed_paths
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi
- if [[ "$SNIFF" == "1" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc;
  fi
- if [[ "$SNIFF" == "1" ]] || [[ "$DEPLOY" == "1" ]]; then npm install -g grunt-cli;
  fi
- if [[ "$SNIFF" == "1" ]] || [[ "$DEPLOY" == "1" ]]; then npm install; fi
- if [[ "$SNIFF" == "1" ]] || [[ "$DEPLOY" == "1" ]]; then npm install -g grunt-checktextdomain;
  fi
script:
- mkdir -p build/logs
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$SNIFF" == "1" ]]; then jshint ./layout/js/*.js; fi
- if [[ "$SNIFF" == "1" ]]; then jscs ./layout/js/*.js; fi
- if [[ "$SNIFF" == "1" ]]; then grunt textdomain; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml
  --extensions=php; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./inc/plugin-activation.php,./node_modules/*.php; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php
  --standard=./phpcs.ruleset.xml --extensions=php --ignore=./node_modules/**/*.php;
  fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/*.php
  --standard=./phpcs.ruleset.xml --extensions=php --ignore=./node_modules/**/**/*.php;
  fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/*.php
  --standard=./phpcs.ruleset.xml --extensions=php --ignore=./node_modules/**/**/**/*.php,./**/**/epsilon-framework/**/*.php;
  fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/**/*.php
  --standard=./phpcs.ruleset.xml --extensions=php --ignore=./node_modules/**/**/**/**/*.php,./**/**/epsilon-framework/**/**/*.php;
  fi
notifications:
  email: false
  slack: macho-themes:5bB622LBK5MkZwDevzAZGC5E
cache:
  directories:
  - node_modules
after_success:
- if [[ "$DEPLOY" == "1" ]]; then grunt build-archive; fi
- if [[ "$DEPLOY" == "1" ]]; then sh set_tags.sh; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: D0woOPu14EtOKQiKoeK43FfgRYTpS4JaCKovgDGZsSS4upKPr3C04BuSJIYBxpg1N4XK5sElmHbu1qmX+GXE38Xies3m6kGLRpAe02KoE63AkXJ3b4CfC20plejR6ixE6YFuF0RTw7lhNQlmpR2vBLjd25a9AErDsQobk9mFpp6xAJFXWJpmLJ2d05UPGVGM6z2ikxRTp+2OB2hvvDNmtNvwd35+jwtHwKmjJpPTvy2JSVHQps7VJOTpTh01crzLeLcKwxuam2PE9lYtzyF1vqD6b8/FvcbjiHQ3K88TmLTOLYrjZb1OCDRpNQQDY0jmgCCPO5uABwzqB5JeCssdn7GTumCCEGcIRxCa587I5VV8NNbXeNRnmLoTFUOsTau+Ky4Nn+TeNgP+Y+GjRZTl7yYHTSqL7Gvj8LtoACs3jgzb3nqBsvAhv8k2V1Uvkbd7bo26ahRbFXvVU3Zv86ET7Fgk8VvLlfcfXbMEb+ioTRVk44LiLESY1VzYSWiEvpujYj/WHqln/7AEufiuJGf/h5vYXwsjAtuH6MXC7lP9Ae0yC+CcRutvGaILjx/uSK2NdZkSSwHzdzu1zx/vhLZ9MFVmpHJx9V3ZXZQvipm7wBzmvvVvgw3WjvkjQz+VMBNZR2FPFsyMnKb0Lie/Btk8MOCSfbawcx2cEhzd+UdgFUQ=
  file: regina-lite.zip
  on:
    repo: MachoThemes/regina-lite
    branch: 'production'
    condition: "$DEPLOY = 1"
